
<div id="faq">
    <div class="content">
        <div class="row">
            <div class="col-12 title" align="center">
                <h2 class="font-g cl-gray-300 f-weight-400"><b>Perguntas e respostas</b> </h2>
            </div>
            <div class="col-lg-4 col-md-12 box">
                <img class="mb-none" src="assets/img/home/faq/image.svg">
                <span class="font-g cl-blue-700 f-weight-700">Ainda está com dúvidas?</span>
                <p class="cl-gray-300 font-s">Acesse nossa Central de atendimento e tire suas dúvidas. Clique abaixo:</p>
                <a href="https://intercom.help/contabilix-598cd4338efb/pt-BR/" target="_blank" class="bt bg-green-200 cl-white font-m">CENTRAL DE ATENDIMENTO</a>
            </div>

            <div class="col-lg-8 col-md-12 faqs">
                <ul>
                    <li>
                        <a href="javascript:;" class="bg-gray-100 cl-gray-300 font-s button-faq f-weight-700 active">O que é a Contabilix? <i class="fa fa-sort-right icon cl-green-200"></i></a>
                        <div class="text active">
                            <span class="font-s cl-blue-400">Somos um Escritório de Contabilidade Online.</span>
                            <p class="cl-gray-300 font-s">Graças a automatização de todas as tarefas executadas nos escritórios tradicionais, conseguimos ter preços incríveis para a contabilidade da sua empresa.
                                Disponibilizamos online suas Demonstrações Contábeis, tais como: Folha de Pagamentos, Impostos, Livro Caixa, Relatórios e outros, além de realizar todas as obrigações legais da sua empresa perante todas as esferas do governo.</p>
                        </div>
                    </li>

                    <li>
                        <a href="javascript:;" class="bg-gray-100 cl-gray-300 font-s button-faq f-weight-700">Por que devo migrar para Contabilidade Online? <i class="fa fa-sort-right icon cl-green-200"></i></a>
                        <div class="text">
                            <p class="cl-gray-300 font-s">
                                O primeiro motivo sem dúvida alguma é a drástica redução de custos para sua empresa, você economiza até 90% do de seu gasto atual com contador.
                                <br /><br />
                                Devemos ressaltar também a liberdade e a praticidade que são bem maiores em relação à interação com uma contabilidade tradicional, deixando você mais tranquilo sabendo que têm acesso as suas informações em tempo real e de onde você estiver.
                                <br /><br />
                                Você receberá alertas pela plataforma e também por e-mail sempre que suas guias de impostos e demais documentos estiverem disponíveis para impressão.
                                <br /><br />
                                E não é só isso, com os processos tendo sido automatizados em nossa Plataforma, temos mais tempo para nos dedicar a sua empresa, nos tornando mais do que contadores, e sim consultores de negócios para auxiliar na melhora de sua gestão empresarial.
                            </p>
                        </div>
                    </li>

                    <li>
                        <a href="javascript:;" class="bg-gray-100 cl-gray-300 font-s button-faq f-weight-700">Preciso de Certificado Digital para utilizar a Contabilix? <i class="fa fa-sort-right icon cl-green-200"></i></a>
                        <div class="text">
                            <p class="cl-gray-300 font-s">
                                Sim. Para todos os tipos de empresa será necessário o Certificado Digital e-CNPJ modelo A1 (arquivo digital).
                            </p>
                        </div>
                    </li>

                    <li>
                        <a href="javascript:;" class="bg-gray-100 cl-gray-300 font-s button-faq f-weight-700">Quais serviços estão inclusos na mensalidade? <i class="fa fa-sort-right icon cl-green-200"></i></a>
                        <div class="text">
                            <p class="cl-gray-300 font-s">
                                Ao se tornar cliente da Contabilix você contará com todos os serviços descritos abaixo já inclusos no valor da mensalidade:<br />
                                Todas as obrigações legais com Receita Federal, Estado e Prefeitura;<br />
                                Cálculo e emissão das guias de impostos;<br />
                                Envio do Imposto de Renda da Empresa anual - IRPJ (ECF, DEFIS);<br />
                                Relatórios contábeis: DRE, Balanço Patrimonial, Balancete, Livro Caixa e etc;<br />
                                Obrigações acessórias como: DCTF, SPED e etc;<br />
                                Emitir notas fiscais eletrônicas pela plataforma;<br />
                                Atendimento dedicado via central de ajuda, chat e telefone;<br />
                                Assessoria completa nas áreas: Trabalhista, Societária, Contábil e Fiscal;
                            </p>
                        </div>
                    </li>

                    <li>
                        <a href="javascript:;" class="bg-gray-100 cl-gray-300 font-s button-faq f-weight-700">O que eu terei que fazer durante o mês? <i class="fa fa-sort-right icon cl-green-200"></i></a>
                        <div class="text">
                            <p class="cl-gray-300 font-s">
                                Durante o mês você terá apenas que imprimir e pagar as guias de impostos e importar o extrato bancário da sua empresa 1x por mês.
                            </p>
                        </div>
                    </li>

                    <li>
                        <a href="javascript:;" class="bg-gray-100 cl-gray-300 font-s button-faq f-weight-700">Tenho funcionários. Vocês fazem a folha de pagamento? <i class="fa fa-sort-right icon cl-green-200"></i></a>
                        <div class="text">
                            <p class="cl-gray-300 font-s">
                                Sim. A folha de pagamento de funcionários está inclusa na sua mensalidade.

                            </p>
                        </div>
                    </li>

                    <li>
                        <a href="javascript:;" class="bg-gray-100 cl-gray-300 font-s button-faq f-weight-700">Como faço para acessar os documentos da minha empresa? <i class="fa fa-sort-right icon cl-green-200"></i></a>
                        <div class="text">
                            <p class="cl-gray-300 font-s">
                                Tenha tudo a um clique de você! Os documentos da sua empresa ficam sempre disponíveis em sua Área do Cliente na Plataforma, deste modo poderá acessá-los de onde estiver, 24hs por dia.

                            </p>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>