
<div id="faq">
    <div class="content">
        <div class="row">
            <div class="col-12 title" align="center">
                <h2 class="font-g cl-gray-300 f-weight-400"><b>Perguntas e respostas</b> </h2>
            </div>
            <div class="col-lg-4 col-md-12 box">
                <img class="mb-none" src="assets/img/home/faq/image.svg">
                <span class="font-g cl-blue-700 f-weight-700">Ainda está com dúvidas?</span>
                <p class="cl-gray-300 font-s">Acesse nossa Central de atendimento e tire suas dúvidas. Clique abaixo:</p>
                <a href="https://intercom.help/contabilix-598cd4338efb/pt-BR/" target="_blank" class="bt bg-green-200 cl-white font-m">CENTRAL DE ATENDIMENTO</a>
            </div>

            <div class="col-lg-8 col-md-12 faqs">
                <ul>
                    <li>
                        <a href="javascript:;" class="bg-gray-100 cl-gray-300 font-s button-faq f-weight-700 active">O que é a Contabilix? <i class="fa fa-sort-right icon cl-green-200"></i></a>
                        <div class="text active">
                            <span class="font-s cl-blue-400">Somos um Escritório de Contabilidade Online.</span>
                            <p class="cl-gray-300 font-s">Graças a automatização de todas as tarefas executadas nos escritórios tradicionais, conseguimos ter preços incríveis para a contabilidade da sua empresa.
                                Disponibilizamos online suas Demonstrações Contábeis, tais como: Folha de Pagamentos, Impostos, Livro Caixa, Relatórios e outros, além de realizar todas as obrigações legais da sua empresa perante todas as esferas do governo.</p>
                        </div>
                    </li>

                    <li>
                        <a href="javascript:;" class="bg-gray-100 cl-gray-300 font-s button-faq f-weight-700">O que é a Contabilix? <i class="fa fa-sort-right icon cl-green-200"></i></a>
                        <div class="text">
                            <span class="font-s cl-blue-400">Somos um Escritório de Contabilidade Online.</span>
                            <p class="cl-gray-300 font-s">Graças a automatização de todas as tarefas executadas nos escritórios tradicionais, conseguimos ter preços incríveis para a contabilidade da sua empresa.
                                Disponibilizamos online suas Demonstrações Contábeis, tais como: Folha de Pagamentos, Impostos, Livro Caixa, Relatórios e outros, além de realizar todas as obrigações legais da sua empresa perante todas as esferas do governo.</p>
                        </div>
                    </li>

                    <li>
                        <a href="javascript:;" class="bg-gray-100 cl-gray-300 font-s button-faq f-weight-700">O que é a Contabilix? <i class="fa fa-sort-right icon cl-green-200"></i></a>
                        <div class="text">
                            <span class="font-s cl-blue-400">Somos um Escritório de Contabilidade Online.</span>
                            <p class="cl-gray-300 font-s">Graças a automatização de todas as tarefas executadas nos escritórios tradicionais, conseguimos ter preços incríveis para a contabilidade da sua empresa.
                                Disponibilizamos online suas Demonstrações Contábeis, tais como: Folha de Pagamentos, Impostos, Livro Caixa, Relatórios e outros, além de realizar todas as obrigações legais da sua empresa perante todas as esferas do governo.</p>
                        </div>
                    </li>

                    <li>
                        <a href="javascript:;" class="bg-gray-100 cl-gray-300 font-s button-faq f-weight-700">O que é a Contabilix? <i class="fa fa-sort-right icon cl-green-200"></i></a>
                        <div class="text">
                            <span class="font-s cl-blue-400">Somos um Escritório de Contabilidade Online.</span>
                            <p class="cl-gray-300 font-s">Graças a automatização de todas as tarefas executadas nos escritórios tradicionais, conseguimos ter preços incríveis para a contabilidade da sua empresa.
                                Disponibilizamos online suas Demonstrações Contábeis, tais como: Folha de Pagamentos, Impostos, Livro Caixa, Relatórios e outros, além de realizar todas as obrigações legais da sua empresa perante todas as esferas do governo.</p>
                        </div>
                    </li>

                    <li>
                        <a href="javascript:;" class="bg-gray-100 cl-gray-300 font-s button-faq f-weight-700">O que é a Contabilix? <i class="fa fa-sort-right icon cl-green-200"></i></a>
                        <div class="text">
                            <span class="font-s cl-blue-400">Somos um Escritório de Contabilidade Online.</span>
                            <p class="cl-gray-300 font-s">Graças a automatização de todas as tarefas executadas nos escritórios tradicionais, conseguimos ter preços incríveis para a contabilidade da sua empresa.
                                Disponibilizamos online suas Demonstrações Contábeis, tais como: Folha de Pagamentos, Impostos, Livro Caixa, Relatórios e outros, além de realizar todas as obrigações legais da sua empresa perante todas as esferas do governo.</p>
                        </div>
                    </li>

                </ul>
            </div>
        </div>
    </div>
</div>