
        <footer id="footer">
            <div id="footer-1" class="bg-blue-900">
                <div class="content">
                    <div class="row">
                        <div class="col-lg-3 col-md-12 ">
                            <img src="../assets/img/logo/logo-white.svg">
                            <ul class="redes">
                                <li>
                                    <a href="javascript:;" class="cl-blue-400 bg-white">
                                        <i class="fa fa-instagram"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:;" class="cl-blue-400 bg-white">
                                        <i class="fa fa-facebook"></i>
                                    </a>
                                </li>

                                <li>
                                    <a href="javascript:;" class="cl-blue-400 bg-white">
                                        <i class="fa fa-linkedin"></i>
                                    </a>
                                </li>

                                <li>
                                    <a href="javascript:;" class="cl-blue-400 bg-white">
                                        <i class="fa fa-whatsapp"></i>
                                    </a>
                                </li>

                            </ul>
                        </div>

                        <div class="col-lg-2 col-md-12 mb-none">
                            <ul>
                               <li>
                                    <a href="/empresa.php" class="cl-white font-s">Abrir Empresa Grátis</a>
                                </li>
                                <li>
                                    <a href="/contador.php" class="cl-white font-s">Trocar de Contador</a>
                                </li>
                                <li>
                                    <a href="/quanto-custa.php" class="cl-white font-s">Quanto Custa</a>
                                </li>
                                <li>
                                    <a href="/sobre-nos.php" class="cl-white font-s">A Contabilix</a>
                                </li>
                                <li>
                                    <a href="javascript:;" class="cl-white font-s">Blog</a>
                                </li>
                            </ul>
                        </div>

                        <div class="col-lg-2 col-md-12 mb-none">
                            <ul class="">
                                <li>
                                    <a href="https://intercom.help/contabilix-598cd4338efb/pt-BR/" target="_blank" class="cl-white font-s">Central de Atendimento</a>
                                </li>
                                <li>
                                    <a href="javascript:;" class="cl-white font-s">Política de Privacidade</a>
                                </li>
                                <li>
                                    <a href="https://www.contabilix.com.br/files/pdfs/CRC-SP_Contabilix.pdf" target="_blank" class="cl-white font-s">Registro no CRC</a>
                                </li>
                                <li>
                                    <a href="javascript:;" class="cl-white font-s">Termos de Uso</a>
                                </li>
                            </ul>
                        </div>

                        <div class="col-lg-5 col-md-12">
                            <p class="cl-white font-pp bd-left">
                                <b>CONTABILIX CONTABILIDADE ONLINE</b><br>
                                CNPJ: 24.199.855/0001-51
                                | CRC: 2SP039590/O-8<br>
                                Av. Marques de São Vicente, 405. Sala
                                1110. Barra Funda.<br>
                                São Paulo/SP. Cep: 01.139-001<br>
                                <b>Fone</b>: 3003 8384
                            </p>
                        </div>
                    </div>

                    <div class="row bd-top">
                        <div class="col-6">
                            <p class="font-pp italic cl-white">
                                A Contabilix é um escritório de contabilidade online. Desenvolvemos um sistema contábil para ajudar as empresas brasileiras com uma contabilidade acessível tanto pelo preço, quanto pela praticidade no dia a dia. Somos um time de consultores, contadores e desenvolvedores apaixonados por contabilidade e tecnologia.
                            </p>
                        </div>
                        <div class="col-6 lt-ft">
                            <p class="font-pp cl-white"><a href="javascript:;" class="cl-white font-pp">Clique aqui</a> e consulte nosso registro do Conselho Federal de Contabilidade</p>
                            <img src="../assets/img/footer/icons-crc.svg">
                        </div>
                    </div>
                </div>
            </div>
            <div id="footer-2">
                <div class="content">
                    <div class="row">
                        <div class="col-lg-6 col-md-12 al-ft2 " align="left">
                            <p class="cl-white font-pp">2020 © Todos direitos reservados. <b>Contabilix</b></p>
                        </div>
                        <div class="col-lg-6 col-md-12 al-ft2" align="right">
                            <p class="cl-white font-pp">Feito por <img src="../assets/img/logo/logo-cr2.png"></p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>


        <div id="barra-fixa">
            <div class="content">
                <div class="row">
                    <div class="col-4">
                        <div class="left">
                            <img src="../assets/img/footer/icon-bar-1.svg">
                            <p class="font-pp cl-gray-300">
                                <b>Está com dúvidas?</b><br>
                                Agende uma ligação ou nos chame no WhatsApp
                            </p>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="center">
                            <a href="javascript:;" class="bt bg-green-200 cl-white font-m f-weight-700">AGENDAR LIGAÇÃO</a>
                            <a href="javascript:;" class="bt bg-blue-400 cl-white font-m f-weight-700"><img src="../assets/img/footer/icon-bar-2.svg">3003 8384</a>
                        </div>
                        </div>
                    <div class="col-4">
                        <form method="post" class="right">
                            <label class="row no-gutters" align="right">
                                <input class="col-10" type="text" name="news" placeholder="Insira seu e-mail e receba nossas novidades">
                                <button class="col-2" type="submit"><img src="../assets/img/footer/icon-bar-3.svg"></button>
                            </label>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div id="modal-load"></div>

    </body>
</html>