
        <footer id="footer">
            <div id="na-midia" class="bg-gray-100">
                <div class="content">
                    <div class="row">
                        <div class="col-2 title-left" align="left">
                            <h2 class="font-g cl-gray-300 f-weight-400"><b>Na mídia</b> </h2>
                        </div>

                        <div class="col-10">
                            <div class="box">
                                <img src="assets/img/home/midia/logo-2.svg">
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div id="footer-1" class="bg-blue-900">
                <div class="content">
                    <div class="row">
                        <div class="col-3">
                            <img src="../assets/img/logo/logo-white.svg">
                            <ul class="redes">
                                <li>
                                    <a href="javascript:;" class="cl-blue-400 bg-white">
                                        <i class="fa fa-instagram"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:;" class="cl-blue-400 bg-white">
                                        <i class="fa fa-facebook"></i>
                                    </a>
                                </li>

                                <li>
                                    <a href="javascript:;" class="cl-blue-400 bg-white">
                                        <i class="fa fa-linkedin"></i>
                                    </a>
                                </li>

                                <li>
                                    <a href="javascript:;" class="cl-blue-400 bg-white">
                                        <i class="fa fa-whatsapp"></i>
                                    </a>
                                </li>

                            </ul>
                        </div>

                        <div class="col-2">
                            <ul>
                               <li>
                                    <a href="javascript:;" class="cl-white font-s">Abrir Empresa Grátis</a>
                                </li>
                                <li>
                                    <a href="javascript:;" class="cl-white font-s">Trocar de Contador</a>
                                </li>
                                <li>
                                    <a href="javascript:;" class="cl-white font-s">Quanto Custa</a>
                                </li>
                                <li>
                                    <a href="javascript:;" class="cl-white font-s">A Contabilix</a>
                                </li>
                                <li>
                                    <a href="javascript:;" class="cl-white font-s">Blog</a>
                                </li>
                            </ul>
                        </div>

                        <div class="col-2">
                            <ul class="">
                                <li>
                                    <a href="javascript:;" class="cl-white font-s">Central de Atendimento</a>
                                </li>
                                <li>
                                    <a href="javascript:;" class="cl-white font-s">Política de Privacidade</a>
                                </li>
                                <li>
                                    <a href="javascript:;" class="cl-white font-s">Registro no CRC</a>
                                </li>
                                <li>
                                    <a href="javascript:;" class="cl-white font-s">Termos de Uso</a>
                                </li>
                            </ul>
                        </div>

                        <div class="col-5">
                            <p class="cl-white font-pp bd-left">
                                <b>CONTABILIX CONTABILIDADE ONLINE</b><br>
                                CNPJ: 24.199.855/0001-51
                                | CRC: 2SP039590/O-8<br>
                                Av. Marques de São Vicente, 405. Sala
                                1110. Barra Funda.<br>
                                São Paulo/SP. Cep: 01.139-001<br>
                                <b>Fone</b>: 3003 8384
                            </p>
                        </div>
                    </div>

                    <div class="row bd-top">
                        <div class="col-6">
                            <p class="font-pp italic cl-white">
                                A Contabilix é um escritório de contabilidade online. Desenvolvemos um sistema contábil para ajudar as empresas brasileiras com uma contabilidade acessível tanto pelo preço, quanto pela praticidade no dia a dia. Somos um time de consultores, contadores e desenvolvedores apaixonados por contabilidade e tecnologia.
                            </p>
                        </div>
                        <div class="col-6 lt-ft">
                            <p class="font-pp cl-white"><a href="javascript:;" class="cl-white font-pp">Clique aqui</a> e consulte nosso registro do Conselho Federal de Contabilidade</p>
                            <img src="../assets/img/footer/icons-crc.svg">
                        </div>
                    </div>
                </div>
            </div>
            <div id="footer-2">
                <div class="content">
                    <div class="row">
                        <div class="col-6 al-ft2 " align="left">
                            <p class="cl-white font-pp">2020 © Todos direitos reservados. <b>Contabilix</b></p>
                        </div>
                        <div class="col-6 al-ft2" align="right">
                            <p class="cl-white font-pp">Feito por <img src="../assets/img/footer/logocr2.svg_"></p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

    </body>
</html>