<!doctype html>
<html>
<head>
    <base href="/" />
    <meta name="author" content="https://somocollab.com">
    <meta charset="UTF-8">
    <meta name="format-detection" content="telephone=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=750px, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-status-bar-style" content="black-translucent">
    <title>CONTABILIX</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" media="screen" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="./assets/css/animate.css" media="screen" rel="stylesheet" type="text/css">
    <link href="./assets/css/assets/css/normalize.css" media="" rel="stylesheet" type="text/css">
    <link href="./assets/css/assets/css/hover.css" media="screen" rel="stylesheet" type="text/css">
    <link href="./assets/css/main.css" media="" rel="stylesheet" type="text/css">
    <link href="./assets/js/extension/owl/owl.carousel.min.css" media="screen" rel="stylesheet" type="text/css">
    <link href="./assets/js/extension/owl/owl.theme.default.min.css" media="screen" rel="stylesheet" type="text/css">
    <link href="./assets/css/responsive/main-responsive.css" media="" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-1.12.3.min.js"   integrity="sha256-aaODHAgvwQW1bFOGXMeX+pC4PZIPsvn2h1sArYOhgXQ="   crossorigin="anonymous"></script>
    <script type="text/javascript" src="./assets/js/form.js"></script>
    <script type="text/javascript" src="./assets/js/extension/owl/owl.carousel.min.js"></script>
    <script type="text/javascript" src="./assets/js/main.js"></script>
    <script type="text/javascript" src="./assets/js/jquery.mask.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
</head>
<body>
    <header id="header">
        <nav class="content">
            <div class="row">
                <div class="col-lg-3 col-md-8 logo" align="left">
                    <a href="/">
                        <img src="../../assets/img/logo/logo-principal.png" alt="Logo Contabilix">
                    </a>
                </div>
                <div class="col-lg-6 col-md-4 menu-desk">
                    <a href="javascript:;" class="menu-open d-block" onclick="$('header nav').toggleClass('active');"><span></span></a>

                    <ul class="menu">
                        <li>
                            <a href="/empresa.php" class="cl-gray-300 font-s">Abrir Empresa Grátis</a>
                        </li>
                        <li>
                            <a href="/contador.php" class="cl-gray-300 font-s">Trocar de Contador</a>
                        </li>
                        <li>
                            <a href="/quanto-custa.php" class="cl-gray-300 font-s">Quanto Custa?</a>
                        </li>
                        <li class="desk-none">
                            <a href="/sobre-nos.php" class="cl-gray-300 font-s">A Contabilix</a>
                        </li>
                        <li class="desk-none">
                            <a href="javascript;;" class="cl-gray-300 font-s">Sistema de Contabilidade</a>
                        </li>
                        <li class="desk-none">
                            <a href="javascript;;" class="cl-gray-300 font-s">Continuar processo de abertura</a>
                        </li>
                        <li class="desk-none">
                            <a href="javascript;;" class="cl-gray-300 font-s">Continuar processo de transferência</a>
                        </li>
                        <li class="desk-none">
                            <a href="javascript:;" class="bt bg-green-200 cl-white font-m">Entrar </a>
                        </li>
                    </ul>
                </div>
                <div class="col-3 menu-right mb-none">
                    <ul>
                        <li>
                            <a href="javascript:;" class="bt bg-green-200 cl-white font-m">Entrar <i class="fa fa-sort-down icon cl-white"></i></a>
                            <ul class="menu-hover">
                                <li>
                                    <a href="javascript;;" class="cl-gray-300 font-s">Sistema de Contabilidade</a>
                                </li>
                                <li>
                                    <a href="javascript;;" class="cl-gray-300 font-s">Continuar processo de abertura</a>
                                </li>
                                <li>
                                    <a href="javascript;;" class="cl-gray-300 font-s">Continuar processo de transferência</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>